// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViziLogin.Data;

#nullable disable

namespace ViziLogin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ViziLogin.Models.Area", b =>
                {
                    b.Property<int>("Id_Area")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Area");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id_Area = 1,
                            Nome = "Barreiro"
                        },
                        new
                        {
                            Id_Area = 2,
                            Nome = "Centro-Sul"
                        },
                        new
                        {
                            Id_Area = 3,
                            Nome = "Leste"
                        },
                        new
                        {
                            Id_Area = 4,
                            Nome = "Nordeste"
                        },
                        new
                        {
                            Id_Area = 5,
                            Nome = "Noroeste"
                        },
                        new
                        {
                            Id_Area = 6,
                            Nome = "Norte"
                        },
                        new
                        {
                            Id_Area = 7,
                            Nome = "Oeste"
                        },
                        new
                        {
                            Id_Area = 8,
                            Nome = "Pampulha"
                        },
                        new
                        {
                            Id_Area = 9,
                            Nome = "Venda Nova"
                        });
                });

            modelBuilder.Entity("ViziLogin.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAvaliador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Nota")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<int>("ServicoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("ServicoId");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("ViziLogin.Models.Denuncia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDenuncia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("ViziLogin.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNotificacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Lida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioDestino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("ViziLogin.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Preco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profissional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("ViziLogin.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Id_Area")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_Area");

                    b.Property<DateTime?>("Inclusao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobre")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonePessoal")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneServico")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_Perfil")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Id_Area");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ViziLogin.Models.Avaliacao", b =>
                {
                    b.HasOne("ViziLogin.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("ViziLogin.Models.Denuncia", b =>
                {
                    b.HasOne("ViziLogin.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("ViziLogin.Models.Servico", b =>
                {
                    b.HasOne("ViziLogin.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ViziLogin.Models.Usuario", b =>
                {
                    b.HasOne("ViziLogin.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("Id_Area");

                    b.Navigation("Area");
                });
#pragma warning restore 612, 618
        }
    }
}
